### ISSUE TITLE
You punished an innocent

### ISSUE THREAD

**Issue by sen1** [triple-jay/Murder-Mystery#5]
The result does not seem correct. Here is the correct answer: check your code to find what went wrong:
```
murderer_sample = TextSample(murder_note, 'Anonymous')
lily_sample     = TextSample(lily_trebuchet_intro, 'Lily Trebuchet')
myrtle_sample   = TextSample(myrtle_beech_intro, 'Myrtle Beech')
gregg_sample    = TextSample(gregg_t_fishy_intro, 'Gregg T. Fishy')
for sample in [lily_sample, myrtle_sample, gregg_sample, murderer_sample]:
    print(sample.author)
    print(find_text_similarity(sample, murderer_sample))
```
results should be:
```
Lily Trebuchet
0.743886853540087 0.7986577181208053 0.11683848797250859
0.553127686544467
Myrtle Beech
0.0031220730565095778 0.3915343915343915 0.018461538461538463
0.13770600101747985
Gregg T. Fishy
0.9075464243382063 0.3793103448275862 0.027950310559006212
0.43826902657493294
Anonymous
1.0 1.0 1.0
1.0
```

**Comment by triple-jay** [comment]
Thank you for your feedback! Could you possibly show me your code for the ngram similarity? The instructions were kind of confusing, and I don't know if I did it right.

**Comment by sen1** [comment]
Here it is:
```
def frequency_comparison(table1, table2):
    appearances = 0
    mutual_appearances = 0
    for key in table1:
        if key in table2:
            value1 = table1.get(key)
            value2 = table2.get(key)
            if value2:
                if value1 > value2:
                    mutual_appearances += value2
                    appearances += value1
                else:
                    mutual_appearances += value1
                    appearances += value2
            else:
                appearances += value1
        else:
            appearances = table1.get(key)

    keys_not_in_table1 = [key for key in table2 if key not in table1]
    for key in keys_not_in_table1:
        appearances += table2.get(key)

    return mutual_appearances / appearances
```

I think you might have gotten this one wrong as well:
```
def get_average_sentence_length(text):
    no_questions = text.replace('?', '.')
    no_exclaim = no_questions.replace('!', '.')
    sentences = no_exclaim.split('.')
    sentence_lengths = []
    
    for sentence in sentences:
        words = sentence.split()
        sentence_lengths.append(len(words))

    average = sum(sentence_lengths) / len(sentence_lengths)
    return average
```

**Comment by triple-jay** [comment]
Thank you for your quick reply and willingness to help me get the correct answer :)! However, with all due respect, I feel as though my average sentence length method is already correct. I checked online with the website https://wordcounttools.com and got the same answer for each text input that I put in. For example, the murder note had an average sentence length of 22.1 according to the website, corresponding with my answer of 22.0666 (when rounded up). As another example, the Myrtle Beech note got me an average sentence length of 6.8, corresponding with my answer again of 6.75 (when rounded up). I tried testing your method, but I got an average sentence length of around 6.51. Is my method still wrong?

**Comment by triple-jay** [comment]
Also, about your code for the frequency comparison, what is the purpose of the "if value2:"? Since you checked right before this if the key is present in table2, wouldn't this mean that value2 would **have** to be greater than 0? After all, a frequency table would not have a key with a corresponding value of 0. Also, what should I do according to your code if both tables have the same key with an equal value? Shouldn't there be a statement that adds this value to both appearances and mutual appearances? Finally, I wanted to ask about your statement "appearances = table1.get(key)". Shouldn't this be +=? Otherwise, this would reset the value of appearances, making it extremely small every time a key in table1 is not in table2. Thank you for taking the time to read my responses!
